fix decorators and config
T-H-C-B/my_raytracer pull request #54
Opened 2023-05-08 17:57 UTC by Bartoszkk

2023-05-08 19:24 UTC, Bartoszkk commented
pire chose de ma vie le wrapper...
quelle idee de le rajouter quand 90% du code est fini

2023-05-08 19:56 UTC, ClementLagasse requested changes

2023-05-08 19:56 UTC, ClementLagasse commented on scenes/basic_scene.cfg
> -Sphere = ({
Remet la scene comme le dev stp

2023-05-08 19:56 UTC, ClementLagasse commented on sources/Core/Core.cpp
> -: image(1920, 1080), _isRunning(true), _catchErrors(false), _configDir(configDir), _pluginDir(pluginDir), _imageUpdated(true), _ambientLight(0.1f), _renderingPercentage(0.1) ,_entityFactory(), _decor
Override pas

2023-05-08 19:56 UTC, ClementLagasse commented on sources/Core/Core.cpp
> +            camera->rotate(RayTracer::Shared::Vec3(0, 1, 0));
Override pas

2023-05-08 19:56 UTC, ClementLagasse commented on sources/Core/Core.cpp
> +            camera->rotate(RayTracer::Shared::Vec3(0, -1, 0));
Override pas

2023-05-08 19:56 UTC, ClementLagasse commented on sources/Core/Core.cpp
> +            camera->rotate(RayTracer::Shared::Vec3(1, 0, 0));
Override pas

2023-05-08 19:56 UTC, ClementLagasse commented on sources/Core/Core.cpp
> +            camera->rotate(RayTracer::Shared::Vec3(-1, 0, 0));
Override pas

2023-05-08 19:56 UTC, ClementLagasse commented on sources/Core/SceneManager.cpp
> +                        _scenes.push_back(std::make_unique<RayTracer::Core::Scene>(filePath));
Override pas

2023-05-08 19:56 UTC, ClementLagasse commented on sources/Core/SceneManager.cpp
> +                        _scenes.push_back(std::make_unique<RayTracer::Core::Scene>(filePath));
Override pas

2023-05-08 19:56 UTC, ClementLagasse commented on sources/Plugins/Decorator/FlatColor/FlatColorEntryPoint.cpp
> +#include "SettingWrapper.hpp"
Include en haut ?

2023-05-08 19:56 UTC, ClementLagasse commented on sources/Plugins/GraphModule/POC/PocEntryPoint.cpp
> +#include "SettingWrapper.hpp"
incude en haut ?

2023-05-08 19:56 UTC, ClementLagasse commented on sources/Plugins/GraphModule/SFML/SFMLEntryPoint.cpp
> +#include "SettingWrapper.hpp"
incude en haut ?

2023-05-08 19:56 UTC, ClementLagasse commented on sources/Plugins/Lights/Ambient/AmbientLightEntryPoint.cpp
> +#include "SettingWrapper.hpp"
incude en haut ?

2023-05-08 19:56 UTC, ClementLagasse commented on sources/Plugins/Primitives/Cones/ConesEntryPoint.cpp
> +#include "SettingWrapper.hpp"
incude en haut ?

2023-05-08 19:56 UTC, ClementLagasse commented on sources/Plugins/Primitives/Cylinders/CylinderEntryPoint.cpp
> +#include "SettingWrapper.hpp"
incude en haut ?

2023-05-08 19:56 UTC, ClementLagasse commented on sources/Plugins/Primitives/Plane/Plane.cpp
> +RayTracer::Plugins::Primitives::Plane::Plane(const RayTracer::Shared::Vec3 &axis, const RayTracer::Shared::Vec3 &position)
override pas

2023-05-08 19:56 UTC, ClementLagasse commented on sources/Plugins/Primitives/Plane/Plane.hpp
> +                Plane(const RayTracer::Shared::Vec3 &axis, const RayTracer::Shared::Vec3 &position);
override pas

2023-05-08 19:56 UTC, ClementLagasse commented on sources/Plugins/Primitives/Plane/PlaneEntryPoint.cpp
> +    if (setting.exists("axis")) {
override pas

2023-05-08 19:56 UTC, ClementLagasse commented on sources/Plugins/Primitives/Plane/PlaneEntryPoint.cpp
> +            const RayTracer::Shared::SettingWrapper &settingposition = setting.lookup<RayTracer::Shared::SettingWrapper>("position");
override pas

2023-05-08 19:56 UTC, ClementLagasse commented on sources/Plugins/Primitives/Spheres/SpheresEntryPoint.cpp
> +#include "SettingWrapper.hpp"
include en haut ?

2023-05-08 19:56 UTC, ClementLagasse commented on sources/Plugins/SkyBox/BlueSkyBox/BlueSkyBoxEntryPoint.cpp
> +#include "SettingWrapper.hpp"
Include en haut

2023-05-08 19:56 UTC, ClementLagasse commented on sources/Plugins/SkyBox/PNGSkyBox/PNGSkyBoxEntryPoint.cpp
> +#include "SettingWrapper.hpp"
Include en haut ?

2023-05-09 10:34 UTC, ClementLagasse approved these changes

2023-05-09 10:34 UTC, merged